### ISSUE TITLE
Implement Whisper Model

### ISSUE THREAD

**Issue by MarcoDotIO** [OpenDive/OpenAIKit#36]
### Describe the feature or improvement you're requesting

https://platform.openai.com/docs/api-reference/audio

**Comment by RickMu** [comment]
This will be super useful!

**Comment by aehlke** [comment]
relevant: https://github.com/ggerganov/whisper.cpp/pull/566

**Comment by MarcoDotIO** [comment]
> relevant: https://github.com/ggerganov/whisper.cpp/pull/566

Thank you! I'll have to look into implementing an option to run via Core ML or using OpenAI's server.

**Comment by aehlke** [comment]
it's been merged just now!

**Comment by MarcoDotIO** [comment]
Closed with v2.0 https://github.com/OpenDive/OpenAIKit/commit/55cc10e406bba124f908dcebe54f3cd62529d3f7
