### ISSUE TITLE
Suggestion: rename class to OpenAIKit

### ISSUE THREAD

**Issue by stormychel** [OpenDive/OpenAIKit#42]
Since I use this in combination with a few other packages, I noticed everyone wants to name their class OpenAI, which makes sense but is quite confusing.

Please consider renaming class to OpenAIKit...

I will create a branch with this change for personal use, and propose a Pull Request to this repo.

**Comment by stormychel** [comment]
Ok I see the problem why the class has been named OpenAI instead of OpenAIKit, the latter conflicts with the package name: 'ContentPolicyParameters' is not a member type of class 'OpenAIKit.OpenAIKit' 🤔
Will rename this to something else and still provide a PR, although it will probably be declined.

**Comment by MarcoDotIO** [comment]
I'd be more than happy to take a look at a better naming convention for the class.
