### ISSUE TITLE
Implement Chat GPT Plugins

### ISSUE THREAD

**Issue by MarcoDotIO** [OpenDive/OpenAIKit#43]
### Describe the feature or improvement you're requesting

https://platform.openai.com/docs/plugins/introduction

### Additional context

I'm currently looking for any volunteer developers who have access to Chat GPT's plugin feature to help develop the feature set for OpenAIKit. I'm currently in the process of figuring out how this feature can be implemented into this existing SDK.

**Comment by stormychel** [comment]
I requested acces and would be glad to help you out if OpenAI lets me in on this.

**Comment by MarcoDotIO** [comment]
![image](https://github.com/MarcoDotIO/OpenAIKit/assets/20867620/ee12bfb0-8f08-43d9-b74a-1fb222a69d4e)

Very good news for this enhancement!

**Comment by MarcoDotIO** [comment]
Plugins aren't currently available for the API endpoints, however the closest solution is using ChatGPT Functions

Closed with v2.0 https://github.com/OpenDive/OpenAIKit/commit/55cc10e406bba124f908dcebe54f3cd62529d3f7
