### ISSUE TITLE
Poll: Should this repo become "AIKit"?

### ISSUE THREAD

**Issue by MarcoDotIO** [OpenDive/OpenAIKit#45]
### Describe the feature or improvement you're requesting

Here's where I'm at with the current project:

I'm almost done with implementing a CoreML implementation for Whisper with OpenAIKit. And I've already completed the streaming data functions, along with the endpoint for Whisper.

Recently though, I've been thinking of moving this project from being OpenAI-centric to being an SDK focusing on AI implementation within the Swift ecosystem. So this would include projects like Stable Diffusion, ElevenLabs, Uber Duck, and so many more awesome AI projects: both from API endpoints to local CoreML models.

I'm now asking the community here: should this project have a broader focus on implementing more AI models and become known as "AIKit", or is it just fine to leave it as OpenAIKit and focus on OpenAI API features directly?

AIKit vote would be a thumbs up, OpenAIKit vote would be a thumbs down, and anything in between can go in the replies of this issue.

Thank you everyone for your continued support of this project.

**Comment by jtnessler** [comment]
Marco:  What did you decide to do with this idea?

**Comment by MarcoDotIO** [comment]
Closed: Decision is to leave OpenAIKit as is.
