### ISSUE TITLE
Add Support for Dall E 3 Image Requests

### ISSUE THREAD

**Issue by bikoo** [OpenDive/OpenAIKit#47]
### Describe the feature or improvement you're requesting

The Dall-E image API now supports model selection, with the default model being Dall-E 2. Dall-E 3 provides much higher image quality, new resolution options, and the ability to request higher detail images (at a higher cost).

It would be awesome if we could get support for the additional features OpenAI released for image creation.

https://platform.openai.com/docs/api-reference/images/create

**Comment by MarcoDotIO** [comment]
Hello,

We are currently migrating the repo. The migration should be done by the end of this week. Once migration is done, Dall-E 3 will be added for support. Once the support is added, we will close this issue. Thank you for your continued support.

**Comment by MarcoDotIO** [comment]
Closed with v2.0 https://github.com/OpenDive/OpenAIKit/commit/55cc10e406bba124f908dcebe54f3cd62529d3f7
